-- Create database
CREATE DATABASE IF NOT EXISTS tp1 CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS SEGMENT;
-- Create segment table
CREATE TABLE SEGMENT
(
    N_SEGMENT VARCHAR(10) NOT NULL,
    NOM_SEGMENT VARCHAR(20),

    CONSTRAINT PK_SEGMENT_N_SEGMENT PRIMARY KEY (N_SEGMENT)
);

DROP TABLE IF EXISTS SALLE;
-- Create salle table
CREATE TABLE SALLE
(
    N_SALLE VARCHAR(7) NOT NULL,
    NOM_S VARCHAR(20),
    NB_POSTE INTEGER(3),
    N_SEGMENT VARCHAR(10) NOT NULL,

    CONSTRAINT PK_SALLE_N_SALLE PRIMARY KEY (N_SALLE),
    CONSTRAINT FK_SALLE_N_SALLE FOREIGN KEY (N_SEGMENT)
    REFERENCES SEGMENT(N_SEGMENT)
);

DROP TABLE IF EXISTS POSTE;
-- Create poste table
CREATE TABLE POSTE
(
    N_POSTE VARCHAR(7) NOT NULL,
    NOM_P VARCHAR(20),
    N_SEGMENT VARCHAR(10) NOT NULL,
    AD VARCHAR(3),
    TYPE_P VARCHAR(6),
    N_SALLE VARCHAR(7) NOT NULL,

    CONSTRAINT PK_POSTE_N_POSTE PRIMARY KEY (N_POSTE),
    CONSTRAINT FK_POSTE_N_SEGMENT FOREIGN KEY (N_SEGMENT)
    REFERENCES SEGMENT(N_SEGMENT),
    CONSTRAINT FK_POSTE_N_SALLE FOREIGN KEY (N_SALLE)
    REFERENCES SALLE(N_SALLE)
);

DROP TABLE IF EXISTS LOGICIEL;
-- Create logiciel table
CREATE TABLE LOGICIEL
(
    N_LOG VARCHAR(5) NOT NULL,
    NOM_L VARCHAR(20),
    DATE_ACH DATE,
    VERSION VARCHAR(7),
    TYPE_L VARCHAR(6),

    CONSTRAINT PK_LOGICIEL_N_LOG PRIMARY KEY (N_LOG)
);

DROP TABLE IF EXISTS INSTALLER;
-- Create installer table
CREATE TABLE INSTALLER
(
    N_POSTE VARCHAR(7) NOT NULL,
    N_LOG VARCHAR(5) NOT NULL,
    DATE_INS DATE,

    CONSTRAINT PK_INSTALLER_N_POSTE_N_LOG PRIMARY KEY (N_POSTE, N_LOG),
    CONSTRAINT FK_INSTALLER_N_POSTE FOREIGN KEY (N_POSTE)
    REFERENCES POSTE(N_POSTE),
    CONSTRAINT FK_INSTALLER_N_LOG FOREIGN KEY (N_LOG)
    REFERENCES LOGICIEL(N_LOG)
);