-- Question 1
CREATE VIEW LOGICIELS_UNIX(N_LOG, NOM_L, DATE_ACH, VERSION, TYPE_L, NB_INSTALL)
AS 
SELECT *
FROM logiciel
WHERE TYPE_L= 'UNIX'

-- Question 2
CREATE VIEW POSTE_0(NPOS0, NSAL0, TYP0, NSEG0, A0)
AS
SELECT NOM_P, N_SALLE, TYPE_P, N_SEGMENT, AD
FROM POSTE
WHERE N_SEGMENT = (SELECT N_SEGMENT
                    FROM SEGMENT 
                    WHERE ETAGE = 0);

-- Question 3
CREATE VIEW SALLE_PRIX(N_SALLE, NOM_S, NB_POSTE, PRIX_LOCATION)
AS
SELECT N_SALLE, NOM_S, NB_POSTE, (100 * NB_POSTE)
FROM SALLE 
GROUP BY N_SALLE

-- Question 4
CREATE VIEW SALLE_POSTE(NOM_S, NOM_P, N_SEGMENT, AD, TYPE_P)
AS
SELECT S.NOM_S, P.NOM_P, P.N_SEGMENT, P.AD, P.TYPE_P
FROM POSTE AS P, SALLE AS S 
WHERE P.N_SALLE = S.N_SALLE

ALTER TABLE TYPE ADD Tarifs INT;

-- Question 5

-- Question 6

-- Question 7
CREATE OR REPLACE VIEW POSTE_0(NPOS0, NSAL0, TYP0, NSEG0, A0)
AS
SELECT NOM_P, N_SALLE, TYPE_P, N_SEGMENT, AD
FROM POSTE
WHERE N_SEGMENT = (SELECT N_SEGMENT
                   FROM SEGMENT
                   WHERE ETAGE = 0)
WITH CHECK OPTION;

